#!/bin/sh
set -eu
cd "$(dirname "$0")"
if [ ! -f node_modules/katex/package.json ]; then
  echo "KaTeX is missing. Run 'npm ci' first." >&2
  exit 1
fi
mkdir -p dist
rm -f dist/zotero-ask-*.xpi
python3 - <<'PY'
import base64
import json
import re
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

root = Path.cwd()
version = json.loads((root / "manifest.json").read_text())["version"]
katex_root = root / "node_modules" / "katex"
katex_dist = katex_root / "dist"
pinned = json.loads((root / "package.json").read_text())["dependencies"]["katex"]
installed = json.loads((katex_root / "package.json").read_text())["version"]
if installed != pinned:
    raise SystemExit(f"KaTeX {installed} is installed but package.json pins {pinned}. Run 'npm ci'.")

# The reader page gets KaTeX's stylesheet as text, so each font is inlined as a woff2 data URI
# instead of being fetched from a URL inside the XPI.
css = (katex_dist / "katex.min.css").read_text()
font_faces = css.count("@font-face")

def inline_font(match):
    data = base64.b64encode((katex_dist / "fonts" / f"{match.group(1)}.woff2").read_bytes()).decode("ascii")
    return f'src:url(data:font/woff2;base64,{data}) format("woff2")'

css, inlined = re.subn(r'src:url\(fonts/([\w-]+)\.woff2\) format\("woff2"\)(?:,url\([^)]*\) format\("[^"]*"\))*', inline_font, css)
if inlined != font_faces or "url(fonts/" in css:
    raise SystemExit(f"Inlined {inlined} of {font_faces} KaTeX fonts; the KaTeX stylesheet format changed.")
katex_style = f"// Generated by build.sh from KaTeX {installed} (MIT). Fonts are inlined as woff2 data URIs.\nvar ZoteroAskKatexCSS = {json.dumps(css)};\n"

output = root / "dist" / f"zotero-ask-{version}.xpi"
with ZipFile(output, "w", ZIP_DEFLATED) as archive:
    for name in ["manifest.json", "bootstrap.js", "core.js"]:
        archive.write(root / name, name)
    archive.write(katex_dist / "katex.min.js", "vendor/katex/katex.min.js")
    archive.write(katex_root / "LICENSE", "vendor/katex/LICENSE")
    archive.writestr("vendor/katex/katex-style.js", katex_style)

with ZipFile(output) as archive:
    names = set(archive.namelist())
    missing = {"vendor/katex/katex.min.js", "vendor/katex/katex-style.js", "vendor/katex/LICENSE"} - names
    if missing:
        raise SystemExit(f"XPI is missing {sorted(missing)}")
    if archive.read("vendor/katex/katex-style.js").decode().count("data:font/woff2;base64,") != font_faces:
        raise SystemExit("XPI KaTeX stylesheet does not embed every font.")
print(f"{output} (KaTeX {installed}, {font_faces} fonts inlined)")
PY
# Exercise the shipped bootstrap.js + core.js combination from inside the XPI.
xpi=$(ls dist/zotero-ask-*.xpi)
if ! ZOTERO_ASK_XPI="$xpi" node --test tests/shipped.test.cjs > /dev/null; then
  echo "Shipped XPI check failed. Rerun: ZOTERO_ASK_XPI=$xpi node --test tests/shipped.test.cjs" >&2
  exit 1
fi
echo "Shipped XPI check passed"
